[package]
name = "pid-ns-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
errno = "0.2.8"
caps = "0.5.3"
